spring:
  datasource:
    url: jdbc:mysql://localhost:3306/man
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: local

  application:
    name: tony

  security:
    user:
      name: user
      password: 1234

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /swagger.html
    use-root-path: true
